language: haskell

ghc:
  - 7.10

before_install:
  - mkdir -p ~/.local/bin
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack install --install-ghc alex happy
  - stack setup

script:
  - stack build --test
