language: haskell

ghc:
  - 7.6
  - 7.8

before_install:
  - cabal update && cabal install alex && cabal install happy 
  - export PATH="$HOME/.cabal/bin:$PATH"

script: 
  - cabal configure --enable-tests && cabal build && cabal test
