# Adapted from:
# https://docs.haskellstack.org/en/stable/travis_ci/

sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal --install-ghc install alex happy

install:
  - stack --no-terminal test --only-dependencies

script:
  - stack --no-terminal test
